### ISSUE TITLE
如何使用redux-logger?

### ISSUE THREAD

**Issue by daCapricorn** [sorrycc/dva-boilerplate-electron#11]
```javascript
import dva from 'dva';
import createLogger from 'redux-logger';

import './main-dev.html';

// 1. Initialize
const app = dva();

// 2. Plugins
app.use(createLogger());
```

加上
```javascript
app.use(createLogger());
```
后页面显示不出来

**Comment by cartooncatfish** [comment]
应该改为：
import { createLogger } from 'redux-logger';

import dva, { connect } from 'dva';
import { Router, Route } from 'dva/router';
import styles from './index.less';

// 1. Initialize
const app = dva();

// 2. Plugins
app.use({
  onAction: createLogger(),
});

**Comment by nelhu** [comment]
> 应该改为：
> import { createLogger } from 'redux-logger';
> 
> import dva, { connect } from 'dva';
> import { Router, Route } from 'dva/router';
> import styles from './index.less';
> 
> // 1. Initialize
> const app = dva();
> 
> // 2. Plugins
> app.use({
> onAction: createLogger(),
> });

解决了我的问题， 
![image](https://user-images.githubusercontent.com/24311105/48928559-4ffdf900-ef1b-11e8-91a5-0ebfa503adbc.png)guan官网的demo有一处错误，应该是import { createLogger } from 'redux-logger';而不是import createLogger from 'redux-logger';
