### ISSUE TITLE
运行示例出现加载 index.css 的错误

### ISSUE THREAD

**Issue by superRaytin** [sorrycc/dva-boilerplate-electron#17]
clone 示例仓库，未做任何修改的情况下，控制台报 index.less 资源错误，见下图：

![image](https://user-images.githubusercontent.com/2723376/35048937-7abc9682-fbd9-11e7-83ff-b443a2716792.png)

**Comment by sorrycc** [comment]
dev 模式下 css 是内联引入的，忽略吧。
