### ISSUE TITLE
运行npm run dev,没有报错但是没能生成main.js和renderer.js到相应的目录下

### ISSUE THREAD

**Issue by 190589751** [sorrycc/dva-boilerplate-electron#3]
本地运行npm run dev,没有报错但是没能生成main.js和renderer.js到相应的目录下,导致运行 npm run start无法使用electron启动项目。
"dev": "webpack -w --config ./webpack.config.main.babel.js & webpack-dev-server --config webpack.config.dev.babel.js",
这个设置如果改为
"dev": "webpack-dev-server --config webpack.config.dev.babel.js & webpack -w --config ./webpack.config.main.babel.js",
就是将“&”前后代码换一下位置就可以生成main.js,但是项目开启时却没能引入renderer.js

备注：操作系统Windows10，node：v6.9.3

**Comment by smackgg** [comment]
@190589751 
没在windows下进行测试，你试一下在两个终端窗口分别运行
`webpack -w --config ./webpack.config.main.babel.js`
`webpack-dev-server --config webpack.config.dev.babel.js`

再新开窗口运行`npm run start`

猜测是你的Linux终端不能在一个窗口同时运行两个webpack。

**Comment by 190589751** [comment]
@smackgg 谢谢！这样是可以的，应该是操作系统的差异问题。还有windows中0.0.0.0与linux中0.0.0.0好像也有差异。

**Comment by smackgg** [comment]
@190589751 
你先这样启动，等我提个PR，改一下这里，在有些系统可能确实存在这个问题。
当时为了少开一个窗口才这样写的。
还是应该改回去，开三个窗口。
你可以把package.json 改成

```
"devServer": "webpack-dev-server --config webpack.config.dev.babel.js",
"dev": "webpack -w --config ./webpack.config.main.babel.js"
```

然后分别在三个窗口运行 `npm run devServer `    `npm run dev `   ` npm run start`

**Comment by 190589751** [comment]
@smackgg   ok，谢谢大大。

**Comment by sorrycc** [comment]
应该修复了，用了下 [concurrently](https://www.npmjs.com/package/concurrently) 。
