### ISSUE TITLE
img路径问题

### ISSUE THREAD

**Issue by flicker85** [sorrycc/dva-boilerplate-electron#4]
请问，在react中根据数据源动态添加img标签，src路径应该怎么写？图片文件应该放在哪个目录下？

**Comment by smackgg** [comment]
图片放在 `src/renderer/assets/`
可以参考 https://github.com/emododododo/daying 项目
`src/renderer/components/webview.js`

代码这样写：
```
const arrowLeft = require('../assets/arrow_left.png');
<img className={goBackClassNames} src={arrowLeft} alt="" />
```

**Comment by flicker85** [comment]
@smackgg 可以了，谢谢~
