### ISSUE TITLE
这个脚手架不可用啊!

### ISSUE THREAD

**Issue by zhengfaning** [sorrycc/dva-boilerplate-electron#6]
npm i 成功后
npm run dev
然后在另一个终端:
npm start
electron显示的是空白画面
不知道是什么原因

**Comment by zhengfaning** [comment]
找到原因了,原来electron在dev环境下缺省load文件是8000端口的。我开了酷狗听歌，酷狗的服务kgservice把8000端口占用了

**Comment by flytam** [comment]
@zhengfaning  你好，你用这个能打包exe文件吗？我报了各种缺少包
