### ISSUE TITLE
如何打包exe文件？

### ISSUE THREAD

**Issue by flytam** [sorrycc/dva-boilerplate-electron#7]
你好请问如何打包exe文件，不太明白

**Comment by flytam** [comment]
为什么打包的时候缺少各种依赖的

**Comment by Jaycexx** [comment]
错误信息：
![m ytmvhkx8u 1__vyh ae](https://cloud.githubusercontent.com/assets/5203240/25474323/666552a4-2b65-11e7-9afe-d16930157445.png)

**Comment by miaosun009** [comment]
@329530588  你的打包问题解决了吗？

**Comment by espring** [comment]
根目录的package.json中scripts下rebuild那行改一下, 去掉./app后面的内容.

```
"rebuild": "electron-rebuild -d=https://gh-contractor-zcbenz.cnpmjs.org/atom-shell/dist/ -m ./app",
```

原因不详, 改了后没有上面的出错信息, 打包成功.
